# Generated by Django 4.0.5 on 2022-06-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reading_time', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('writing_time', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('math_ci_time', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('math_ca_time', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('science_time', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('break1_time', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('break2_time', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('break3_time', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('break4_time', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
