# Generated by Django 4.0.5 on 2022-06-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='user',
            field=models.TextField(null=True),
        ),
    ]
