# Generated by Django 4.0.5 on 2022-06-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_monitor_app', '0002_testmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='essay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='reading_1_time',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='reading_2_time',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='test_type',
            field=models.CharField(default='SAT', max_length=3),
        ),
    ]
