# Generated by Django 4.0.5 on 2022-06-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_monitor_app', '0003_testmodel_essay_testmodel_reading_1_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='break4_time',
            new_name='before_essay_break',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='test_type',
            new_name='test',
        ),
    ]
