# Generated by Django 4.0.5 on 2022-06-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_monitor_app', '0004_rename_break4_time_testmodel_before_essay_break_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='writing_time',
            new_name='english_time',
        ),
    ]
