# Generated by Django 4.0.5 on 2022-06-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_monitor_app', '0005_rename_writing_time_testmodel_english_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='before_essay_break',
            new_name='before_essay_break_time',
        ),
    ]
