# Generated by Django 4.0.5 on 2022-07-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_monitor_app', '0007_remove_testmodel_essay_testmodel_essay_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='before_essay_break_time',
            new_name='before_essay_break_time_act',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='break1_time',
            new_name='before_essay_break_time_sat',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='break2_time',
            new_name='before_essay_break_time_sat_acc',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='break3_time',
            new_name='break1_time_act',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='english_time',
            new_name='break1_time_sat',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='essay_time',
            new_name='break1_time_sat_acc',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='math_ca_time',
            new_name='break2_time_sat',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='math_ci_time',
            new_name='break2_time_sat_acc',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='reading_1_time',
            new_name='break3_time_sat_acc',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='reading_2_time',
            new_name='english_time_act',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='reading_time',
            new_name='english_time_sat',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='science_time',
            new_name='english_time_sat_acc',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='essay_time_act',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='essay_time_sat',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='essay_time_sat_acc',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='math_ca_time_act',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='math_ca_time_sat',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='math_ca_time_sat_acc',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='math_ci_time_sat',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='math_ci_time_sat_acc',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='reading_1_time_sat_acc',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='reading_2_time_sat_acc',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='reading_time_act',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='reading_time_sat',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='science_time_act',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
