from django.db import models

# Create your models here.
class testModel(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.TextField(null=True)
    test = models.CharField(max_length=3, default="SAT")
    accommodations = models.BooleanField(default=False)
    reading_time_sat = models.TextField(max_length=6, null=True)
    break1_time_sat = models.TextField(max_length=6, null=True)
    english_time_sat = models.TextField(max_length=6, null=True)
    math_ci_time_sat = models.TextField(max_length=6, null=True)
    break2_time_sat = models.TextField(max_length=6, null=True)
    math_ca_time_sat = models.TextField(max_length=6, null=True)
    before_essay_break_time_sat = models.TextField(max_length=6, null=True)
    essay_time_sat = models.TextField(max_length=6, null=True)
    reading_1_time_sat_acc = models.TextField(max_length=6, null=True)
    break1_time_sat_acc = models.TextField(max_length=6, null=True)
    reading_2_time_sat_acc = models.TextField(max_length=6, null=True)
    break2_time_sat_acc = models.TextField(max_length=6, null=True)
    english_time_sat_acc = models.TextField(max_length=6, null=True)
    math_ci_time_sat_acc = models.TextField(max_length=6, null=True)
    break3_time_sat_acc = models.TextField(max_length=6, null=True)
    math_ca_time_sat_acc = models.TextField(max_length=6, null=True)
    before_essay_break_time_sat_acc = models.TextField(max_length=6, null=True)
    essay_time_sat_acc = models.TextField(max_length=6, null=True)
    english_time_act = models.TextField(max_length=6, null=True)
    math_ca_time_act = models.TextField(max_length=6, null=True)
    break1_time_act = models.TextField(max_length=6, null=True)
    reading_time_act = models.TextField(max_length=6, null=True)
    science_time_act = models.TextField(max_length=6, null=True)
    before_essay_break_time_act = models.TextField(max_length=6, null=True)
    essay_time_act = models.TextField(max_length=6, null=True)